
title: "Kshitij's Scribbles"
description: Scratchpad for my thoughts
url: http://Kshitij-Banerjee.github.io/Blog
permalink: ':title/'

markdown: kramdown
baseurl: "/Blog"


sass:
    style: compressed


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: UA-50428840-2

# Comments
disqus-shortname: kshitij-banerjee

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token: 285384b0b437f217b4fc0c7d8f69cc8a

include: [_pages]
version: 1.0

gems: [jekyll-paginate, jekyll-seo-tag]
